routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Routes For Admin Dashboard

// login + logout
    Route::group(['prefix'=>'admin/dashboard','namespace'=>'admin'],function() {
    Route::get('admin-login', 'AdminDashboardController@showLogin')->name('adminLogin');
    Route::post('adminLogin', 'AdminDashboardController@adminLogin')->name('adminDashboardLogin');
    Route::get('admin-logout', 'AdminDashboardController@adminLogout')->name('adminLogout')->middleware('Admin');
    //Route::post('adminLogout', 'AdminDashboardController@logout')->middleware('Admin');
});

Route::group(['prefix'=>'admin','namespace'=>'admin','middleware'=>'Admin'],function() {
        //Routes For Employee
        Route::group(['prefix' => 'employee'], function () {
        Route::get('all', 'EmployeeController@index')->name('allEmployee');
        Route::post('add-employee', 'EmployeeController@store')->name('addEmployee');
        Route::get('edit-employee/{employeeId}', 'EmployeeController@edit')->name('editEmployee');
        Route::post('update-employee', 'EmployeeController@update')->name('updateEmployee');
        Route::post('delete-employee', 'EmployeeController@destroy')->name('deleteEmployee');

    });
});

Route::get('/', function () {
    return view('welcome');
});

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
class Employee extends Model
{
    //
    protected $table     = "employees";
    protected $fillable  = ['first_name','last_name','image','job','user_id','status'];
    protected $hidden    = [];
    public    $timestamps= true;

    public function getFullNameAttribute(){
        return ucfirst($this->first_name) .' '. ucfirst($this->last_name);
    }

    public function User(){
        return $this->belongsTo(User::class,'user_id');
    }

    public static function uploadFile($img,$file)
    {
       if(Storage::disk('public')->put($img,file_get_contents($file)))
           return true;
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $table    = 'users';
    protected $fillable = ['user_name','password'];
    public $timestamps=false;
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden =   ['password'];

    public function Employee(){
        return $this->hasOne(Employee::class,'user_id');
    }



}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/admin/AdminDashboardController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Requests\AdminLoginRequest;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
class AdminDashboardController extends Controller
{
    //
    public function showLogin(){
        Auth::user()&&Auth::user()->user_name=='admin95' ? $view=redirect()->route('allEmployee'): $view=view('admin.login');
        return $view;
    }

    public function adminLogin(AdminLoginRequest $request)
    {
        $credentials=[
                       'user_name' => $request['userName'],
                       'password'  => $request['password'],
                     ];
        if(Auth::attempt($credentials))
        {
            return redirect()->route('allEmployee');
        }else{
            return redirect()->route('adminLogin')->with('alert-danger','userName or password not matched ,try again plz !');
        }
    }

    public function adminLogout(Request $request){
        Auth::logout();
        $request->session()->invalidate();
        return redirect()->route('adminLogin');
    }

}

app/Http/Controllers/admin/EmployeeController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use App\Employee;
use Illuminate\Support\Facades\Storage;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct(Employee $model)
    {
        $this->view='admin/employees/';
        $this->model=$model;
    }
    public function index()
    {
        $employees=$this->model->orderBy('created_at','Desc')
                               ->get();
        return view($this->view.'index',compact('employees'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $image   = $request->file('img');
        $imageUploaded=$image->getClientOriginalName();
        //return $request;
        $employee = new Employee();
        $employee->first_name = $request->firstName;
        $employee->last_name  = $request->lastName;
        $employee->user_id    =  $request->userId;
        $employee->job        = $request->job;
        $employee->status     = $request->status;
        $employee->image      = $imageUploaded;
        $employee->save();
        $v=Employee::uploadFile($imageUploaded,$image);
        if ($v==true)
        {
            $employeeBlock=view($this->view.'employee-block',compact('employee'))
                ->render();
            return response()->json(['status'=>true,'employeeBlock'=>$employeeBlock]);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $employee=Employee::find($id);
        if($employee){
        return response()->json(['status'=>true,'employee'=>$employee,'urlImg'=>Storage::url($employee->image)]);
        }
        return response()->json(['status'=>false,'msg'=>'no employee for this']);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {    //return response()->json(['status'=>true,'r'=>$request->all()]);
        if ($image=$request->hasFile('img')){
            $imageUploaded=$image->getClientOriginalName().'.'.$image->getClientOriginalExtension();
        }
        //return $request;
        $employee = Employee::with('User')->find($request->employeeEditedId);
        $employee->first_name = $request->firstName;
        $employee->last_name  = $request->lastName;
        //$employee->user_id  = $request->userId;
        $employee->job        = $request->job;
        $employee->status     = $request->status;
        if ($image) {
            $v = Employee::uploadFile($image,$imageUploaded);
            $employee->image  = $imageUploaded;
        }
        $employee->save();
        return response()->json(['status'=>true,'msg'=>'Updated Successfully','employee'=>$employee]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        $employee=Employee::find($request->id);
        if ($employee)
        {
          $employee->delete();
          return response()->json([
                                   'success' => true,
                                   'msg'     => 'deleted successfully'
                                  ]);
        }
          return response()->json([
                               'success'=> false,
                               'msg'    => 'not found'
                             ]);

    }
}

resources/views/admin/employees/employee-block.blade.php
<tr class = "item-{{ $employee->id }}">
    <td>{{ $employee->full_name }}</td>
    <td><img width="80" height="80" src="{{ asset('$employee->image') }}"></td>
    <td>{{ substr($employee->job,20) }}</td>
    <td>{{ $employee->User->user_name }}</td>
    <td>{{ $employee->status }}</td>
    <td>
        <button data-id="{{ $employee->id }}" data-route="{{ route('editEmployee',['employeeId'=>$employee->id]) }}" class = "btn btn-default button-custom editEmployee" data-toggle = "modal" data-target = "#editModal">
            Edit
        </button>
        <button style="color: white"  data-id="{{ $employee->id }}" data-route="{{ route('deleteEmployee') }}" class="deleteEmployee btn btn-default btn-danger ">
            delete
        </button>
    </td>
</tr>

resources/views/admin/employees/index.blade.php
@extends('admin.layouts.app')
@section('content')
    <div id = "page-wrapper">
        <div class = "container-fluid">
            <div class = "row">
                <div class = "col-lg-12">
                    <h1 class = "page-header"><i class = "fa fa-clone"></i> View/Edit Employees</h1>
                </div>
                <!-- /.col-lg-12 -->
                <div class = "panel panel-default">
                    <div class = "panel-heading">
                        <button class="btn btn-default btn-success" data-toggle="modal" data-target="#addModal">Add Employee</button>
                    </div>
                    <div class = "panel-body">
                        <table width = "100%" id="table" class = "table table-striped table-bordered table-hover datatable" >
                            <thead >
                            <tr>
                                <th>Full Name</th>
                                <th>Image</th>
                                <th>Job</th>
                                <th>UserName</th>
                                <th>Status</th>
                                <th>Operatios</th>
                            </tr>
                            </thead>
                            <tbody class="data-collection">
                            @if(count($employees ))
                            @foreach($employees as $employee)
                            <tr class = "item-{{ $employee->id }}">
                                <td class="td-fullName-{{ $employee->id }}">{{ $employee->full_name }}</td>
                                <td class="td-img-{{ $employee->id }}"><img width="80" height="80" src="{{ asset('storage/'.$employee->image) }}"></td>
                                <td class="td-job-{{ $employee->id }}">{{ substr($employee->job,0,50) }}<span>....</span></td>
                                <td class="td-userName-{{ $employee->id }}">{{ $employee->User->user_name }}</td>
                                <td class="td-status-{{ $employee->id }}">{{ $employee->status }}</td>
                                <td>
                                    <button data-id="{{ $employee->id }}" data-route="{{ route('editEmployee',['employeeId'=>$employee->id]) }}" class = "btn btn-default button-custom editEmployee" data-toggle = "modal" data-target = "#editModal">
                                        Edit
                                    </button>
                                    <button style="color: white"  data-id="{{ $employee->id }}" data-route="{{ route('deleteEmployee') }}" class="deleteEmployee btn btn-default btn-danger ">
                                        delete
                                    </button>
                                </td>
                            </tr>
                                @endforeach

                                 @else
                                  <span class="text-danger lead"> not employees nntil now!</span>
                                 @endif

                            </tbody>
                        </table>
                    </div>
                </div>

                 <!--edit modal-->
                <div class = "modal fade" id = "editModal" role = "form" aria-labelledby = "myModalLabel"
                     aria-hidden = "true">
                    <div class = "modal-dialog  modal-lg">
                        <div class = "modal-content">
                            <div class = "row">
                                <div class = "container-fluid">
                                    <h1 class = "modal-header"><i class = "fa fa-clone"></i> Edit Employee</h1>
                                    <div class = "modal-body">
                                        <div class = "row">
                                            <form role = "form" method="post" enctype="multipart/form-data" class="formEdit" >
                                                        <div class = "col-md-6 col-sm-8">
                                                            <div class = "col-xs-10">
                                                                <img  id="userImage" src="{{ asset('/admin/img/user.png') }}" class="userImageEdit col-xs-12">
                                                                <label class = "btn btn-default button-custom upload-picture col-xs-12">
                                                                    Browse <input  id="uploadFile" name="img" type = "file" class = "hidden">
                                                                </label>
                                                            </div>
                                                        </div>
                                                <div class="form-group col-md-6">
                                                    <label for="firstName" class="text-muted">firstName</label>
                                                    <input type="text" id="firstName" name="firstName" class="form-control firstNameEdit" placeholder="Enter first name" >
                                                </div>
                                                <div class="form-group col-md-6">
                                                    <label for="lastName" class="text-muted">lastName</label>
                                                    <input type="text" name="lastName" id="lastName"class="form-control lastNameEdit"placeholder="Enter last name"  >
                                                </div>
                                                <div class="form-group col-md-6">
                                                    <label for="job" class="text-muted">Job</label>
                                                  <textarea id="job" name="job"class="form-control jobEdit" placeholder="Enter job details" ></textarea>
                                                </div>
                                                <div class="form-group col-md-6">
                                                    <label for="status" class="text-muted">status</label>
                                                  <select name="status" id="status" class="statusEdit form-control">
                                                    <option value="active">active</option>
                                                    <option value="not_active">not active</option>
                                                  </select>
                                                </div>
                                                <input type="hidden" value="" name="employeeEditedId" class="employeeEditedId" >
                                                <div class="form-group col-md-6 pull-right">
                                                                    <button data-route="{{ route('updateEmployee') }}"  type="submit" class="updateEmployee btn btn-default col-md-5 button-custom" style="margin-right: 8px;">
                                                                        Update
                                                                    </button>
                                                    <button type="button" class="btnClose btn btn-default btn-warning" data-dismiss="modal">Close</button>
                                                </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- /.row (nested) -->

                                    </div>
                                </div>

                            </div>
                        </div>

                <!--add modal-->
                <div class = "modal fade" id = "addModal" role = "form" aria-labelledby = "myModalLabel"
                     aria-hidden = "true">
                    <div class = "modal-dialog  modal-lg">
                        <div class = "modal-content">
                            <div class = "row">
                                <div class = "container-fluid">

                                    <h1 class = "modal-header"><i class = "fa fa-clone"></i> Add Employee</h1>

                                    <div class = "modal-body modalAdd">
                                        <div class = "row">
                                            <form role = "form" method="post" class="formAdd" enctype="multipart/form-data">
                                                {{ csrf_field() }}
                                                <div class = "col-md-6 col-xs-10">
                                                    <img  id="userImage" src="{{ asset('/admin/img/user.png') }}" class="user-image col-xs-12">
                                                    <label class = "btn btn-default button-custom upload-picture col-xs-12">
                                                        Browse <input  id="file_uploadImg" name="img" type = "file" class = "hidden imgUserFileAdd"  >
                                                    </label>
                                                </div>
                                                <div class="form-group col-md-6">
                                                    <label for="firstName" class="text-muted">firstName</label>
                                                    <input type="text" id="firstName" name="firstName" class="form-control firstNameAdd" placeholder="Enter first name" >
                                                </div>
                                                <div class="form-group col-md-6">
                                                    <label for="lastName" class="text-muted">lastName</label>
                                                    <input type="text" name="lastName" id="lastName"class="form-control lastNameAdd"placeholder="Enter last name"  >
                                                </div>
                                                <div class="form-group col-md-6">
                                                    <label for="job" class="text-muted">Job</label>
                                                    <textarea name="job" id="job" class="form-control jobAdd" placeholder="Enter job details" ></textarea>
                                                </div>
                                                <div class="form-group col-md-6">
                                                    <label for="status" class="text-muted">status</label>
                                                    <select name="status" id="status" class="statusAdd form-control">
                                                        <option value="active">active</option>
                                                        <option value="not_active">not active</option>
                                                    </select>
                                                </div>
                                                @php
                                                $users=\App\User::where('user_name','!=','admin95')->get();
                                                @endphp
                                                <div class="form-group col-md-6">
                                                    <label for="userId" class="text-muted">userName</label>
                                                    <select name="userId" id="userId" class="userId form-control">
                                                        @foreach($users as $user)
                                                        <option value="{{ $user->id }}">{{ $user->user_name }}</option>
                                                            @endforeach
                                                    </select>
                                                </div>

                                                <div class="form-group col-md-6 pull-right">
                                                    <input data-route="{{ route('addEmployee') }}"  value="Add" type = "submit" class="addEmployee btn btn-default col-md-5 button-custom"  style="margin-right:8px;">
                                                    <button type="button" class="btn btn-default btn-warning btnClose " data-dismiss="modal">Close</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>

                    </div>
                </div>

            </div>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang = "{{ app()->getLocale() }}">
<head>
    <meta charset = "utf-8">
    <meta http-equiv = "X-UA-Compatible" content = "IE=edge">
    <meta name= "viewport" content = "width=device-width, initial-scale=1">
    <meta name= "description" content = "employee app">
    <meta name= "author" content = "Mohamed Hassan Hammam">
    <meta name= "csrf-token" content = "{{ csrf_token() }}">
    <meta name= "url" content = "{{ url('/') }}">

    <title>Admin Panel</title>
    <link   href=  "{{ asset('admin/css/bootstrap.min.css') }}" rel = "stylesheet">
    <link   href=  "{{ asset('admin/css/font-awesome.min.css') }}" rel = "stylesheet">
    <link   href=  "{{ asset('admin/css/style.css') }}" rel = "stylesheet">
    <link   href=  "{{ asset('admin/css/sweetalert.css') }}" rel = "stylesheet">
    <link rel="stylesheet"
          href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css">
</head>
<body>
<div id = "wrapper">
    <nav class = "navbar navbar-default navbar-static-top navbar-fixed-top" role = "navigation" style = "margin-bottom: 0">
        <!-- Just For Coding Fast use @ auth -->
        @auth
        @include('admin.layouts.header')
        @endauth
    </nav>

      @yield('content')
</div>
@include('admin.layouts.footer')
</body>
</html>

resources/views/admin/layouts/footer.blade.php
<footer>
    <p>&copy; Employee App {{ date('Y') }} </p>
</footer>
</div>
<!-- jQuery -->
<script src = "{{ asset('admin/js/jquery.min.js') }}"></script>
<!-- Bootstrap  -->
<script src = "{{ asset('admin/js/bootstrap.min.js')}}"></script>
<script src = "{{ asset('admin/js/sweetalert-dev.min.js')}}"></script>
<script src = "{{ asset('admin/js/ajax.js')}}"></script>
<script src =  "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src =  "https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>

resources/views/admin/layouts/header.blade.php
<div class = "navbar-header">
    <button type = "button" class = "navbar-toggle" data-toggle = "collapse" data-target = ".navbar-collapse">
        <span class = "sr-only">Toggle navigation</span>
        <span class = "icon-bar"></span>
        <span class = "icon-bar"></span>
        <span class = "icon-bar"></span>
    </button>
    <a class = "navbar-brand text-center" href = "{{ route('allEmployee') }} "> Employee App Dashboard </a>
</div>
<ul class = "nav navbar-top-links navbar-left">
    <li><a href = "{{ route('adminLogout') }}" >logout</a>
</ul>

resources/views/admin/login.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Login To Dashboard ..</h3>
                    </div>
                    <div class="panel-body">
                        <form role="form" method="post" action="{{ route('adminDashboardLogin') }}">
                            {{ csrf_field() }}
                            <fieldset>
                                @if($session=Session::get('alert-danger'))
                                    <div class="alert alert-danger">
                                        <div class="media-body">{{ $session }}</div>
                                    </div>
                               @endif
                                <div class="form-group">
                                    <input input="text"   class="form-control" placeholder="Enter your user-name" name="userName" autofocus>

                                @if ($errors->has('userName'))
                                    <span class="text-danger">
                                        <strong>{{ $errors->first('userName') }}</strong>
                                    </span>
                                @endif
                                </div>
                                <div class="form-group">
                                    <input type="password" class="form-control" placeholder="Enter your Password" name="password" >

                                @if ($errors->has('password'))
                                    <span class="text-danger">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                                </div>
                                    <input type="submit" value="Login" class="btn btn-lg button-custom btn-block" style="border: solid 1px #4f96c4;">
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection